murkup+images
OlgaBlud/watch-sharm pull request #2
Opened 2024-03-21 12:59 UTC by Yuliia0905

2024-03-21 15:17 UTC, OlgaBlud requested changes
Все добре завантажується, але давай додамо стилі в css і потім змерджимо.

2024-03-22 16:34 UTC, OlgaBlud requested changes
Зроби декілька маленьких виправлень і можна буде змерджити.

2024-03-22 16:34 UTC, OlgaBlud commented on src/css/reviews.css
> +
Це прибираємо, йде за замовчанням вже
img {
  display: block;
}

2024-03-22 16:34 UTC, OlgaBlud commented on src/css/reviews.css
> +
Для review-title  прибираємо text-align: left; Так воно і є за замовчанням.

2024-03-22 16:34 UTC, OlgaBlud commented on src/css/reviews.css
> +
Для .review-list-item  
min-width: 335px; заміняємо на max-width(бо має бути гумовим до певної ширини)

2024-03-22 16:41 UTC, Yuliia0905 commented on src/css/reviews.css
> +
Спочатку так і зробила, li поводила себе дивно. Зараз зробила все норм)

2024-03-22 16:41 UTC, Yuliia0905 commented on src/css/reviews.css
> +
ок

2024-03-22 16:42 UTC, Yuliia0905 commented on src/css/reviews.css
> +
ок

2024-03-22 21:10 UTC, merged